apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SERVER_ROOT_URL
              value: "{{ .Values.server.root_url }}"
            - name: GF_SMTP_ENABLED
              value: "{{ .Values.smtp.enabled }}"
            - name: GF_SMTP_HOST
              value: "{{ .Values.smtp.host }}"
            - name: GF_SMTP_USER
              value: "{{ .Values.smtp.user }}"
            - name: GF_SMTP_PASSWORD
              value: "{{ .Values.smtp.password }}"
            - name: GF_SMTP_FROM_ADDRESS
              value: "{{ .Values.smtp.from_address }}"
            - name: GF_SMTP_FROM_NAME
              value: "{{ .Values.smtp.from_name }}"
            - name: GF_SMTP_SKIP_VERIFY
              value: "{{ .Values.smtp.skip_verify }}"
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana
