apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dhunn-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/singhupasana467/Dhunn-musicapp.git
    targetRevision: main
    path: musicapp-helm/dhunn-backend-chart

  destination:
    server: https://kubernetes.default.svc
    namespace: musicapp-net
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
