apiVersion: v1
kind: Pod
metadata:
  name: fail-pod
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: crash-container
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["exit 1"]
