apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: musicapp-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "musicdb"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "password"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d
            - name: mysql-pv
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1"
      volumes:
        - name: mysql-init
          hostPath:
            path: "/run/desktop/mnt/host/c/Users/timbe/Documents/docker_setup_musicapp/docker_setup_musicapp/mysqldb_setup/init"
            type: Directory
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc
