apiVersion: v1
kind: Service
metadata:
  name: musicapp-backend
  namespace: musicapp-net
spec:
  selector:
    app: musicapp-backend
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 8080  # Host port
